### ISSUE TITLE
Project references no longer existent branch and classes from stormpath-sdk-java

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-spring-boot-security-webmvc-sample#1]
[`WebSecurityConfig`](https://github.com/stormpath/stormpath-spring-boot-security-webmvc-sample/blob/master/src/main/java/com/stormpath/StormBoot/config/WebSecurityConfig.java) references the classes `EnableStormpathSpringSecurityWebMvcAutoConfiguration ` and `StormpathWebSecurityConfiguration`.

Neither of these classes exist in the [stormpath-sdk-java](https://github.com/stormpath/stormpath-sdk-java) repo.

The [`README`](https://github.com/stormpath/stormpath-spring-boot-security-webmvc-sample/blob/SpringBootStormpathSecurity_101/README.md) for the SpringBootStormpathSecurity_101 tag say you need to checkout and build the `spring-boot_spring-security` branch of the SDK - however this branch no longer exists.

If I look at the SDK log it looks like the classes above stopped being present in any branch long ago.

So is this repo dead? If so it should be clearly marked as so, along with a pointer to the replacement - I guess maybe [stormpath-spring-security-example](https://github.com/stormpath/stormpath-spring-security-example)?

**Comment by dogeared** [comment]
Yes, this project is going to be completely revamped with our Spring Security release this week. Thanks for pointing this out. Going to delete the repo for now.

**Comment by george-hawkins-aa** [comment]
So how to properly create a `WebSecurityConfig` class that can be used with Spring Boot will be covered by something that is going out later this week? Or is it already covered in documentation elsewhere - I couldn't find anything on docs.stormpath.com :disappointed:

**Comment by george-hawkins-aa** [comment]
My current shot at this is the following - but I always get `Expected CSRF token not found. Has your session expired?` after the logon page :disappointed: 

```java
@Configuration
@EnableWebMvcSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
            .antMatchers("/assets/**").permitAll()
            .anyRequest().authenticated();
        
        http
            .formLogin()
                .loginPage("/login")
                .permitAll()
                .defaultSuccessUrl("/", true)
                .and()
            .logout()
                .permitAll();
    }
    
    @Autowired
    private Client client;
    
    // TODO: move value to properties file and inject.
    private final static String APPLICATION_REST_URL = "https://api.stormpath.com/v1/applications/XYZ";
    
    private AuthenticationProvider createAuthenticationProvider() {
        StormpathAuthenticationProvider provider = new StormpathAuthenticationProvider();
        
        provider.setClient(client);
        provider.setApplicationRestUrl(APPLICATION_REST_URL);
        
        return provider;
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder builder) throws Exception {
        builder.authenticationProvider(createAuthenticationProvider());
    }
}
```

Sorry to use an issue as a support request mechanism - if this is all documented somewhere or will be in something soon to be released then that's fine.

**Comment by george-hawkins-aa** [comment]
OK - after more searching about I see [`AbstractStormpathSpringSecurityConfiguration`](https://github.com/stormpath/stormpath-sdk-java/blob/spring_security_extension/extensions/spring/stormpath-spring-security/src/main/java/com/stormpath/spring/config/AbstractStormpathSpringSecurityConfiguration.java) and it's subclass `StormpathSpringSecurityAutoConfiguration` on the spring_security_extension branch. So I guess I should pause on trying to get Stormpath to work with Spring Boot for the moment and wait for these to be merged into a release. Looking forward to it :smile:

**Comment by lhazlewood** [comment]
Hi George!  Sorry for the confusion!  We're working hard today to finalize everything for the release and documenting how this all works (with sample projects).  We'll close this issue out as soon as the release (and the updated documentation) are out.  Cheers!
